### ISSUE TITLE
URDFLoader.js 0.2.0 Release TODO

### ISSUE THREAD

**Issue by gkjohnson** [gkjohnson/urdf-loaders#31]
### Changes
- [x] URDFLoader is Instantiate-able
- [x] Add `setValue` field to update joint angles
- [x] Investigate joint inversion
- [x] Fix rendering inefficiency in element
- [x] Mesh scale (https://github.com/gkjohnson/urdf-loaders/pull/37)
- [x] Separate the example code for use in other repos

**Comment by gkjohnson** [comment]
Released!
